name = "ujicoba2"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.133.223.50"
UUID = "e5110cac-93ad-43d6-87d3-824326c4e16d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
